name: testsuite

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:
  workflow_dispatch:

# I don't think that we can (safely) set TEST_JOBS=2 in the global environment,
# because on Win32 the various Makefile's `test` target is actually ./harness,
# and it would (attempt to) honour the $ENV{TEST_JOBS} setting. This won't end
# nicely as unlike BSD (etc), Win32 sockets can drop data at process exit, which
# would cause missing TAP and hence spurious test failures.

env:
  PERL_SKIP_TTY_TEST: 1
  CONTINUOUS_INTEGRATION: 1

jobs:

  #                 ___  ___
  #  _ __  __ _ __ / _ \/ __|
  # | '  \/ _` / _| (_) \__ \
  # |_|_|_\__,_\__|\___/|___/

  smoke-macos-catalina-xcode12:
    name: "macOS (catalina) xcode 12"
    runs-on: macos-10.15
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        CONFIGURE_ARGS:
          - "-Uusethreads"
          - "-Duseithreads -Duseshrplib"

    steps:
      - uses: actions/checkout@v2
      - name: Install gdbm 1.18
        run: |
          wget https://ftp.gnu.org.ua/gnu/gdbm/gdbm-1.18.tar.gz
          tar xfz gdbm-1.18.tar.gz
          cd gdbm-1.18
          ./configure --without-readline --disable-nls
          make
          make install
      - name: Configure
        run: |
          export SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
          sh ./Configure -des -Dusedevel ${{ matrix.CONFIGURE_ARGS }}
      - name: Build
        run: |
          make -j2 test_prep
      - name: Show Config
        run: |
          ./perl -Ilib -V
          ./perl -Ilib -e 'use Config; print Config::config_sh'
      - name: Run Tests
        run: |
          TEST_JOBS=2 ./perl t/harness -v ext/GDBM_File/t/*.t cpan/Memoize/t/errors.t cpan/Memoize/t/tie_gdbm.t

